### ISSUE TITLE
Don't fail when no controller is detected

### ISSUE THREAD

**Issue by lrusak** [ynsta/steamcontroller#15]
I would like to use this driver with OpenELEC, however it fails to run when no controller is plugged in

> ValueError: SteamControler Device not found

This is problematic because I package this driver as an addon and use systemd to enable and disable it.
So it would be nice if it would just run as a daemon and wait for a device to be turned on/plugged in.

see, https://github.com/lrusak/lrusak-openelec-addons/blob/master/addons/service/driver/steamcontroller/source/systemd/service.driver.steamcontroller.service

As right now I have to restart the service every 10 seconds which isn't ideal.

I would use udev rules but the way addons work in kodi/OpenELEC don't really allow for this.

Thanks for the consideration or any direction you can point me in.

EDIT:
maybe something like this would work?

```
        while self._handle is None:
          for i in range(len(PRODUCT_ID)):
              pid = PRODUCT_ID[i]
              endpoint = ENDPOINT[i]
              ccidx = CONTROLIDX[i]

              self._handle = self._ctx.openByVendorIDAndProductID(
                  VENDOR_ID, pid,
                  skip_on_error=True,
              )

```

**Comment by agboom** [comment]
I have a similar setup in Kodi on a Raspberry Pi 2, but in my case the driver is started in `/etc/rc.local` where `sc-desktop.py start` is invoked. When the wireless adapter is not attached, the driver daemon causes performance problems, probably because it cannot find the device. Every 10 or so seconds the picture stutters slightly. When the wireless adapter is attached, the driver starts fine and there are no stutters.
